[tool.black]
line-length = 100
target-version = ['py37']
include = '''
\.pyi?$
| bubblewrap
'''
exclude = '''
(
  /(
      \.eggs        
    | \.git
    | \.pytest_cache
    | \.venv
    | .gitignore
    | LICENSE
    | README.md
    | requirements.txt
  )/
)
'''

[tool.pytest.ini_options]
markers = [
    "unit: marks tests as unit tests for the project, not demo dirs",
]
